
language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y doxygen texlive-latex-base texlive-latex-extra texlive-fonts-recommended

install:
  - pip install -r requirements/production.txt
  - pip install .

env:
  - TRAVIS_CI=True

# Builds all examples & html documentation
#
# Provide definition for DOXYGEN variable to stop it trying
# to run `which doxygen`
script: make DOXYGEN=doxygen DEBUG=""

