
language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

install: "pip install -r requirements/production.txt"

# Builds all examples & html documentation
#
# Provide definition for DOXYGEN variable to stop it trying
# to run `which doxygen`
script: make DOXYGEN=doxygen

